### PR TITLE
Add tooltips to item names, like tokens

### PR DESCRIPTION
**Pull request by M-Hawkins**
image

I like having the full content, but I know you had trimmed these in other use sites, idk if you'd want to maintain that max length here too. 

image

### CODE REVIEW

**Comment by joshpayette** [comment]
If skill item descriptions cause issues to this fix, can maybe only truncate skill descriptions and show full descriptions for everything else.

**Comment by M-Hawkins** [comment]
Varies, but can definitely get up there.  

image

I'll add a filter on item categories to remove the more verbose and flavor text-y ones (e.g. armor pieces) so we can start small.

**Comment by M-Hawkins** [comment]
Rebased, seems all good still  
I like the new UX

image
image

**Comment by joshpayette** [comment]
> Varies, but can definitely get up there.
> 
> image
> 
> I'll add a filter on item categories to remove the more verbose and flavor text-y ones (e.g. armor pieces) so we can start small.

Is this done so this is ready to merge?

**Comment by M-Hawkins** [comment]
Yup! Added that pre-rebase

https://github.com/joshpayette/remnant2-toolkit/pull/191/files#diff-5986a43933eafa7ab5b209ebda11df5f7d648092965acd717b9861028a55acddR17-R19

**Review by joshpayette — APPROVED** [review]

**Pull request merged**
