### PR TITLE
move [A] tags from end of description to after relevant aoe mention

### PR DESCRIPTION
**Pull request by ThreePixiesInATrenchcoat**

### CODE REVIEW

**Comment by joshpayette** [comment]
@AlexijSeptimus you approve? I think you are specific about tag placement.

**Comment by ThreePixiesInATrenchcoat** [comment]
it's just two mods that I noticed had it differently than all others, this way it's more consistent with other descriptions

**Comment by AlexijSeptimus** [comment]
Amalie is correct

**Comment by joshpayette** [comment]
Great! Wanted to be sure. Will merge after dinner!

**Review by joshpayette — APPROVED** [review]

**Pull request merged**
